### ISSUE TITLE
how does it compare to dom-template-strings

### ISSUE THREAD

**Issue by kapouer** [WebReflection/hyperHTML#108]
I'm really interested in hyperHTML, but the code size looks huge when compared to
https://github.com/kapouer/dom-template-strings.
Surely hyperHTML brings more features, but it's not obvious to me when looking at the documentation.
First thing that looks different is that hyperHTML can run on server ? without jsdom ?

**Comment by WebReflection** [comment]
The NodeJS compatible API is called [viperHTML](https://viperhtml.js.org/viper.html), it gives you same API but it can stream layouts too. And no, it doesn't use jsdom.

Anyway, _dom-tempalte-strings_ does pretty much nothing _hyperHTML_ does:

  * it pollutes global prototype like Node and Document, hyper doesn't
  * it doesn't understand at all attributes, hyper does
  * it doesn't understand events, hyper does
  * it has no mechanism to create components, hyper does
  * it does not update the same node instead of creating new nodes each times, hyper does
  * it's not compatible with partial tables because it trusts incompatible polyfills, hyper is compatible with non template compatible browsers so that the list dom-template-strings shows as compatible, is not actually compatible
  * it doesn't let you reference content to a specific object.
  * it doesn't let you use a node to render and update N times same content.
  * it doesn't meet all [custom elements requirements](https://custom-elements-everywhere.com/#hyperhtml)
  * it doesn't work with Firefox < 55 and TypeScript transpiled code ... hyperHTML does

There is a [list here](https://gist.github.com/WebReflection/fadcc419f5ccaae92bc167d8ff5c611b) and I might go on but instead I'll close this adding that questions are more welcome in StackOverflow, as explained in the [readme](https://github.com/WebReflection/hyperHTML#questions-).

**Comment by kapouer** [comment]
Cool ! In no way it was meant to be rude. Thank you.

**Comment by WebReflection** [comment]
Me neither, and I've just realized that is your library.

If you did check the documentation you would've probably also noticed [all the examples](https://viperhtml.js.org/hyperhtml/examples/#!fw=React&example=Basic%20Component) with live demos against all famous frameworks and the [very first snippet](https://viperhtml.js.org/hyperhtml/documentation/) of the documentation already does something you library cannot do: update only a portion of a content.

Your library just uses `innerHTML` with text, this library first, and recently _lit-html_ too, do way more than that and it's unfortunate you thought it was similar to yours: hyperHTML is a new pattern that has nothing strictly to do with just strings or `innerHTML` per se.

I hope I've clarified differences even further.

Best Regards
