### ISSUE TITLE
Custom renderer?

### ISSUE THREAD

**Issue by dakom** [WebReflection/hyperHTML#123]
Is it possible to use hyperHTML with a custom renderer? The use-case being an equivalent to something like react-native or react-hardware, i.e. no DOM at all.

**Comment by WebReflection** [comment]
See nativeHTML and basicHTML 😉

**Comment by joshgillies** [comment]
This is answered with the opening sentence of the readme.

> A **Fast & Light Virtual DOM Alternative** available for [NodeJS](https://viperhtml.js.org/viper.html) and [NativeScript](https://viperhtml.js.org/native.html) too.

**Comment by dakom** [comment]
@WebReflection - I took a quick look via https://viperhtml.js.org/ ... and I gather there's no simple way to add a custom renderer like if I wanted to drive a robot or something (that's not what I actually need, unfortunately, but it helps to illustrate flexibility questions). Am I correct?

@joshgillies - understood, but I thought there might be like a hidden feature here or something, just making sure from those who actually know the internals and how it's exposed before coming to my own conclusions based on a Readme blurb

**Comment by WebReflection** [comment]
> I gather there's no simple way to add a custom renderer like if I wanted to drive a robot or something

[basicHTML](https://viperhtml.js.org/basic.html) supports Custom Elements but without the W3C Custom Elements limitations. In fact, you can create a `Page` Custom Element, as it's done for [nativeHTML](https://viperhtml.js.org/native.html).

In turns, that means you have all primitives you need to create your own robot driven by HTML, as long as it makes sense to have such abstraction (it does for me, but it feels also overengineered, IMO).

So, the simple way to add a custom render is to use _basicHTML_ on NodeJS, instead of real DOM on browsers, and define your custom render by Custom Elements.

If this is not what you are looking for, please provide concrete examples because my answer to your question is _yes_ but the way you do it is not like React (which I've no idea what way is that ... but if it's via JSX then it's pretty much the exact same way I've just described).
