### ISSUE TITLE
How to set a custom property `fooBar` without setting the attribute `foobar`

### ISSUE THREAD

**Issue by kaste** [WebReflection/hyperHTML#131]
Well I know that attribute names are case insensitive. But given

```
<my-span fooBar="${{name: 'value'}}"></my-span>
```

hyperHTML correctly sets the property `fooBar` to the given value, but it _also_ sets an attribute `foobar` to `[object Object]` which looks ugly. Note that the corresponding attribute I implement in such cases is usually named `foo-bar` anyway, b/c that's the convention in DOM land. 

**Expected** output would be, I guess

```
<my-span></my-span>
```

**Actual** output

```
<my-span foobar="[object Object]"></my-span>
```

**Comment by WebReflection** [comment]
Please read the documentation about attributes. This is a won’t fix / expected behavior as it stands.

The W3C standard is about data- attributes, not any name

**Comment by kaste** [comment]
hyperHTML already sets the property here. It also sets a property when I do ``<input value="${'BAZ'}" />``. So clearly hyperHTML interprets my template and has an opinion on what's the best thing to do.

The output when I do the above  ``<input value="${'BAZ'}" />`` is actually

```
<input/>
```
👍

**Comment by WebReflection** [comment]
the `<input value>` is not "_a property_", it's a well defined accessor in the specification.

the best thing to do with standard behaviors is to use them as such, with custom attributes I've no idea what you are trying to do and since attributes are case insensitive, I've no idea how you are going to aces that.

The documentation describes all valid values:
https://viperhtml.js.org/hyperhtml/documentation/#essentials-4

  * text, as string, for any kind of attribute
  * boolean true or false for special attributes such disabled and others
  * function or object for custom or native events
  * either null or undefined to explicitly remove attributes of any kind, or to remove listeners

The only special case that won't conflict with any future attribute or specs in general is `data`.

If you use `data-atribute` that's for the `dataset` but if you use `data=${anyObject}` that's assigned as it is.

Dealing with undefined, non standards, future hostile behavior is not my plan here.

I've also told you already attributes are complicated and I'd like to add that I have no plan for the time being to make them any more complicated than now.

**Comment by techpanga** [comment]
Is it possible to pass JSON objects( using variables) via attributes?


var loginModel = {user:'john',password:'doe'};
this.html`
<my-login data-model=${loginModel} ></my-login>
`

With in MyLogin component, I am unable to get the attribute using this.dataset.model 

Please help.
