### ISSUE TITLE
readonly attribute

### ISSUE THREAD

**Issue by pinguxx** [WebReflection/hyperHTML#155]
using this code
https://codepen.io/pinguxx/pen/eyOZVy?editors=1010

```
const App = {
  html: hyperHTML.bind(document.querySelector('#app')),
  data: {readonly: true},
  render() {
    this.html`<p> ${this.data.readonly}</p>
    <input readonly="${this.data.readonly ? 'readonly' : null}">`;
  }
};
App.render();

setInterval(function () {
  App.data.readonly = !App.data.readonly;
  App.render();
}, 4000)
```

the input start as readonly correctly but after that when the flag is true again the input never gets the readonly attribute again, not sure what im doing wrong

**Comment by WebReflection** [comment]
Boolean attributes must be Boolean.

Have you tried true / false instead of ‘readonly’ / null ?

**Comment by pinguxx** [comment]
yes it keeps changing to readonly="true" and readonly="false" so its always readonly

https://codepen.io/pinguxx/pen/eyOZVy?editors=1010

```
const App = {
  html: hyperHTML.bind(document.querySelector('#app')),
  data: {readonly: true},
  render() {
    this.html`<p> ${this.data.readonly}</p>
    <input readonly="${this.data.readonly}">`;
  }
};
App.render();

setInterval(function () {
  App.data.readonly = !App.data.readonly;
  App.render();
}, 4000)
```

**Comment by pinguxx** [comment]
oh looks like it has to be readOnly not readonly in the input `<input readOnly=${this.data.readonly}>`

**Comment by papas-source** [comment]
@WebReflection maybe I am wrong, but i believe that this is not the expected behaviour, I mean if `readOnly` works and `readonly` does not.

**Comment by WebReflection** [comment]
attributes always work, attributes accessed as JS properties might need camelCases, which is something I am not planning to change/fix any time soon because it will bloat the code size consistently providing very little gain.

To be clear, if you do this:
```js
hyperHTML.bind(document.body)`<input readonly="${'readonly'}" value=123>`
```
and then you do this
```js
hyperHTML.bind(document.body)`<input readonly="${null}" value=123>`
```
the input switches from `readonly` to regular (no attribute at all) and then it goes back `readonly`.

That is documented: if you want to remove an attribute pass `null`, otherwise pass any value you want to keep it there.

JS attributes are accessors to these caseinsensitive HTML attributes. If you want to directly set them as JS properties, you need to use the JS property way.

This works well even combined with _viperHTML_ on the server side, since true or false will either show or not show at all the attribute.

As summary:

  * using HTML attribute with `null` or a value works
  * using JS accessors via `true` or `false` (or any other value for that accessor) works well too

The HTML specification wouldn't care less if you wrote `onclick` or `onClick`, while XML attributes are always preserved and treated as attributes.

Maybe something to explicit in the documentation, not necessarily something to work around/patch/fix in the library.
