### ISSUE TITLE
Router and State management

### ISSUE THREAD

**Issue by ansarizafar** [WebReflection/hyperHTML#157]
I want to replace Vuejs with awesome hyperHTLM/ViperHTML but Vuejs has an official router which supports SSR and nested routes. Vue also has an event bus. state management,  Nustjs for easily creating SSR applications and ui libraries like Vuetify, vue-meterial and Elementui. Is there equivalent libraries/features available  for hyperHtml. I want to use hyper.Component. I am looking for a complete example or starter project.

**Comment by pinguxx** [comment]
check
https://github.com/WebReflection/hyperhtml-app
and
https://github.com/WebReflection/hyperHTML-Element

**Comment by ansarizafar** [comment]
Is there any example of using hyperhtml with hyperhtml-app router available. Does the router supports nested routing and before/after hooks. Is it possible to add an Vuejs like global event bus. How state is manged with hyperHtml. A complete example app would be very helpful.

**Comment by WebReflection** [comment]
This might be a good example
https://github.com/WebReflection/viper-news

I’ve no idea what’s a global event bus or why would you need one, and state is managed like in Preact

**Comment by pinguxx** [comment]
maybe something like this for events
https://github.com/WebReflection/broadcast

**Comment by ansarizafar** [comment]
hyperHtml has  potential to replace Vdom but better documentation, more examples an updated cli/starter project and a complete router is a must for the success.

**Comment by WebReflection** [comment]
One of the _hyperHTML_ strengths is that it does not lock you in.

The `hyperhtml-app` router is enough for most common cases but you are free to use any route you want.

The state management is very simple, Preact like, but you're free to use any other state management you want.

You can opt in and out of _hyperHTML_ whenever you want, but surely there is room for improvements in all the areas you have mentioned and help is also welcome.

Closing this since I don't see it needing any further hint.
