### ISSUE TITLE
Some examples linked from the documentation pages are broken

### ISSUE THREAD

**Issue by yuretz** [WebReflection/hyperHTML#165]
I was browsing through the documentation & examples, and noticed that the [Hacker News PWA](https://viperhtml-164315.appspot.com/top/1) is actually throwing some exceptions in the console, and if you try clicking some links  (like "comments", or "new" or basically any other internal app links) you'll see that they are not working either.
The [unit test page](https://webreflection.github.io/hyperHTML/test/) linked from the repository README.md is showing some weird error messages in the console too.

I assume these are probably nothing major, but I just mean it might give a potential user a wrong impression about the library, so I decided to just let you know.

**Comment by WebReflection** [comment]
HNPWA has Webpack issues ... I haven't found yet time to inform WebPack team it has issues ...

THe unit test page is green and the errors are SVG overly verbose warnings, nothing that will ever go away from this library, because it's impossible, something already filed to browser vendors.

This library is already used in production and soon planned to be delivered to 100M users without a glitch so ... thanks for opening this but don't worry, it just works as expected.

**Comment by yuretz** [comment]
OK, cool. Thanks for the quick reply.

**Comment by yuretz** [comment]
100 million users? :open_mouth: This sounds impressive! :thumbsup: Now I'm curious how it could be? Of course if you care and are allowed to share the details... Is it going to ship with some major product?

**Comment by WebReflection** [comment]
that's the idea, but I cannot share any extra detail now and I've also edited the number since at the time it'll happen I don't know how many but I hope there will be at least that number.

All I can say is that this library is good enough :wink: and actually very stable.
