### ISSUE TITLE
"Wire" not working in firefox with webcomponents polyfill

### ISSUE THREAD

**Issue by codemeasandwich** [WebReflection/hyperHTML#170]
I just found that, if using firefox & webcomponents polyfill is on the page. Then using a `wire` with a value has broken output.

On Firefox please see: 
https://jsfiddle.net/codemeasandwich/95r3g6ro/
Works find in chrome because it has native webcomponent support

I think this could be a big problem becase [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs) is used in [polymer](https://www.polymer-project.org) meaning [hyperHTML-Element](https://github.com/WebReflection/hyperHTML-Element) cant work on the same page as elements from [webcomponents.org](https://www.webcomponents.org/)

From what I can see. The childnode array from `wire` has each item wrapped in an object with the real node buried inside

Hope this helps

**Comment by chrismbeckett** [comment]
I changed your webcomponents polyfill to load:

//unpkg.com/@webcomponents/webcomponentsjs/webcomponents-lite.js

and it works in Firefox.

**Comment by chrismbeckett** [comment]
I updated your webcomponent polyfill link to try each of the following:

https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@1.0.19/webcomponents-loader.min.js
https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@1.0.19/webcomponents-lite.min.js
https://unpkg.com/@webcomponents/webcomponentsjs/webcomponents-lite.js

and your example worked in firefox for all of them. I think the problem is the source of your webcomponents polyfill.

**Comment by WebReflection** [comment]
for custom elements only I suggest [this polyfill](https://github.com/WebReflection/document-register-element) [backed by Google AMP team itself](https://opencollective.com/document-register-element).

about this issue ... I don't know, everything is fine here: https://jsfiddle.net/3c3d60k1/

basically you have an old polypill that breaks libraries ... but they fixed already, and there's nothing to do here.

when in doubt, consider this page: https://custom-elements-everywhere.com/#hyperhtml
hyperHTML is 100% compatible with Web components (and web standards in general)
