### ISSUE TITLE
NextJs/NuxtJS/SapperJS like framework for hyperHTML

### ISSUE THREAD

**Issue by ansarizafar** [WebReflection/hyperHTML#176]
hyperHtml/ViperHtml is amazing and a NextJs/NuxtJS/SapperJS like framework for hyperHTML will make it popular overnight. Is there any plan to develop a full stack framework?

**Comment by WebReflection** [comment]
something like this ? https://github.com/WebReflection/create-viperhtml-app

**Comment by ansarizafar** [comment]
Something more simpler then create-viperhtml-app. A single package, single configuration file and single Express middleware. Built-in store management, routing and service worker. It can be a compiler like Sappper/Svlete or StencilJs.

**Comment by WebReflection** [comment]
sounds like a lot of work ... and in any case something that won't land directly in this repository.

for the routing I use [hyperhtml-app](https://github.com/WebReflection/hyperhtml-app)

about single Express middleware I've no idea what you are thinking about but viperHTML is already easy to integrate with Express, right?

Built-in store management, any concrete example I can double check?

Also service worker out of the box might not be that simple but I'll investigate.

**Comment by ansarizafar** [comment]
- hperhtml-app has limited feature set. Before/after hooks are required for route authorization. Check https://router.vuejs.org/en/ or https://github.com/Rich-Harris/roadtrip 
- Express middleware to avoid boilerplate, please check Sapper starter https://sapper.svelte.technology/guide#getting-started and nuxt starter https://github.com/nuxt-community/express-template/blob/master/template/server/index.js
- Check Svlete/Sapper store option https://svelte.technology/guide#state-management
- StencilJs is using https://developers.google.com/web/tools/workbox/ to generate service worker. Please also check https://github.com/ionic-team/ionic-pwa-toolkit build with stenciljs.

**Comment by WebReflection** [comment]
Right, a lot of work indeed. Thanks for the links. I'll read when I have time and think about it.

hyperHTML is missing adoption, which is the feature no other framework has ... that's the next big thing on the roadmap. After that, the framework would be somehow _complete_ in terms of client/server rendering potentials and only at that point I can focus on something else like those bootstrappers you mentioned.

Closing since there's no action to take here but thanks for the hint.

**Comment by davidbwaters** [comment]
I've been looking into precaching.  Since a lot of these boilerplates are just modules that use webpack under-the-hood, most of this could be done with this, it looks like: https://www.npmjs.com/package/sw-precache-webpack-plugin
Create-react-app is another boilerplate like this.  It's pretty much a module that uses a webpack config under the hood and exposes part of the webpack config in it's own config file to make it extensible, usually with its own plugins that add a sass step or whatever, without intimidating beginners with a wall of webpack config.  Routing is sometimes automated by having by separating "page" components from other components and having the page components generate routes. 

I'm more comfortable being able to see everything going on and always found these limiting when I'd start with them and switch, but I see the appeal of being able to jump right in and write code for something as complicated as an SSR React PWA that automatically splits code by route, handles routing with a page-like abstraction, and doesn't require webpack knowledge.  For those learning the basics today, it probably seems like they have to learn 20 things to make something.  I started with html and css, eased into js with jquery and then learned the rest.
