### ISSUE TITLE
Using hyperHTML in Edge

### ISSUE THREAD

**Issue by patrickliechty** [WebReflection/hyperHTML#186]
Every other browser is working great, but in Edge browser my site is very slow.  I mean 10x slower than Chrome, Firefox, and Safari.  Are there known issues with Edge?

**Comment by WebReflection** [comment]
No knonw issue with Edge but here there's no link to counter verify, no code to check if it's not a browser issue but a bad usage of the library, no version of Edge or the used OS so I wonder how do you expect me to help.

Can you please improve this bug? Thanks.

**Comment by WebReflection** [comment]
BTW, since you are asking, there is one difference in IE/Edge and is well documented in the code
https://github.com/WebReflection/hyperHTML/blob/master/index.js#L262-L282

Basically IE/Edge `cloneNode(true)` is buggy, Microsoft [knows it](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15839308/), and it's easy to feature detect:
https://github.com/WebReflection/hyperHTML/blob/master/index.js#L226

But saying that is 10X slower seems like a bit extreme so my previous questions remain.

**Comment by patrickliechty** [comment]
Looks like my VM on my mac was slow.  I tried it on a surface pro and it is fast.  Sorry to cry wolf to quickly.

**Comment by WebReflection** [comment]
what a little detail you omitted there ... Edge in VM ... glad it works for real
