### ISSUE TITLE
colspan is not working properly in IE11

### ISSUE THREAD

**Issue by judge** [WebReflection/hyperHTML#205]
Hi,

We tried to build a table with hyperHTML and we would like to add dynamic `colspan` to one of our td elements. It works fine in Chrome, Firefox and Edge, but we got an error in IE11: `Member not found.`

We created a pen: https://codepen.io/jdg/pen/eVXKPx (please open it in IE11).

Could you please check this?
Thanks!

**Comment by papas-source** [comment]
oh that damn browser :(

**Comment by pinguxx** [comment]
try with
colSpan

**Comment by WebReflection** [comment]
Hi @judge , can you actually follow @pinguxx hint and tell me if the wolfing would work ?

```<td colSpan=${options.colspan}>hello</td>```

note the camelCase `colSpan` in the template.

If that's the case I'm afraid there's not much I can do because unless I implement a dictionary of every single attribute that might have a camelCase equivalent for IE11 only it's hard to randomly guess camelCases and exponentially a no-go for performance.

If that's not the case though, I'll try to figure out how to solve this extra shenanigan .

Thanks for your patience (I don't have IE11 with me right now, you might be faster in trying)

**Comment by judge** [comment]
Yes, `colSpan` works, thanks @pinguxx and @WebReflection !
This should be included in the documentation (somehow, I know it's a guess game mostly), I could not find it.
