### ISSUE TITLE
How to use hyperHTML together with Canvas & async actions

### ISSUE THREAD

**Issue by jaschaio** [WebReflection/hyperHTML#210]
Hey there,
take a look at [this codepen](https://codepen.io/jaschaio/pen/OvPZmN).

There is a `onconnected` method which initiates a `makeQuery` method that requests some data from an external source. _(In the codepen I just generate some random number to update the state with)._

Inside the same component is another Method that draws a Chart on a Canvas with the help of [chart.js](https://chartjs.org)

The problem is that the chart is redrawn each time new data comes in from the external source even if it has nothing to do with the data that is drawn on the chart. I am unsure how to prevent this. Would I have to isolate the Canvas Element into another component?

**Comment by albertosantini** [comment]
I followed the flow of the calls:

- `makeQuery()` is a recursive function calling `this.update()`, via `setTimeout`
- `this.update()` calls `this.render()`
- `this.render()` calls `this.renderCanvas()`
- `this.renderCanvas() calls `renderChart()`, creating every time a `new Chart`

I expect exactly what you described: it is not related to hyperHTML, it is about that logic. :)

You may read https://github.com/WebReflection/hyperHTML/issues/103.

**Comment by WebReflection** [comment]
Hi @jaschaio, I cannot control what 3rd parts libraries do.

If you invoke a method that creates a `new Chart...` each time that's it, you're rendering a new Chart every time indeed.

However, if all you need is to know is a reference to that `canvas` element so that you can create that chart off the main render, update, or setState method, you can intercept it via `onconnected` and be done with it, as shown in [this fork of your pen](https://codepen.io/WebReflection/pen/BrobwP?editors=0010).

Hope it's clear how to go in these cases. This is not a bug anyway, so for future questions like this one (i.e. _How to do ..._) please post in Stack Overflow.

Thank you!

**Comment by WebReflection** [comment]
P.S. one thing that really bothered me, but it's not hyperHTML related, is that chart gets slower, and slower, and slower, even if the canvas is cleaned up ... there's something nasty going on with that chart library, watch out multi render on same canvas, it looks like it never release the `requestAnimationFrame` or something similarly nasty
