### ISSUE TITLE
IE11 id and class attributes swapped

### ISSUE THREAD

**Issue by davidmerrique** [WebReflection/hyperHTML#23]
I just ran into a bug in **IE11** where my `class` and `id` attributes and their values are swapped.

This isn't a problem if I declare the class before the id.

```javascript
const id = 'yolo-id'
const classname = 'yolo-class'

const el = hyperHTML.wire()`<div id="${id}" class="${classname}">Yolo</div>`
const el2 = hyperHTML.wire()`<div class="${classname}" id="${id}">Yolo2</div>`

document.body.appendChild(el)
document.body.appendChild(el2)
```

This results in:
```html
<div class="yolo-id" id="yolo-class">Yolo</div> <!-- Wrong! -->
<div class="yolo-class" id="yolo-id">Yolo2</div>
```

Thanks!

**Comment by WebReflection** [comment]
gosh that's interesting, if IE11 orders attributes by name it's going to be fun to fix this one.

That browser is full of hidden evil issues!

Will try to think about a solution, thanks.

**Comment by WebReflection** [comment]
so, apparently a known issue: http://quirksmode.org/dom/core/#t120

the whole `hyperHTML` is based on the assumption the order is the right one, I'm wondering if it makes even sense to fix this issue within this package instead of creating an `hyperHTML-IE` one when IE is needed.

That would simplify this one, and will bloat IE only.

Thoughts?

**Comment by papas-source** [comment]
What a junk browser!!!

I am afraid IE11 will be here for a long time...
So if you decide to make a `hyperHTML-IE` version, it would probably end up being used more that the no-IE version.

BTW, congratulations for your game-changing Job 👍

**Comment by WebReflection** [comment]
turns out, this was easier than expected. Thanks gosh `node.getAttributeNode(name)` works consistently with IE9 and higher.

You can quickly test the fix through the following page:
https://webreflection.github.io/hyperHTML/test/ie.html

If clicking trues story shows "_completely-random,it-does-not-matter_" it works 🎉
