### ISSUE TITLE
Documentation: Clarifications on how wire and node cache works

### ISSUE THREAD

**Issue by cederberg** [WebReflection/hyperHTML#286]
A few things in the documentation wasn't immediately obvious to me:

- **How to update DOM nodes:** It wasn't super-obvious that calling `wire(obj, id)` with same object + id again will actually update previously generated DOM nodes. So function result can be discarded (if nodes are already in page DOM tree).
- **How to NOT update DOM nodes:** Mixing direct DOM node manipulations (e.g. via jQuery) and `wire(obj, id)` doesn't work quite as one might expect. The node cache in `wire` will not detect changes to node attributes that are "static" in the template. Perhaps not changes to DOM tree structure either?
- **Can the DOM node cache be cleared?** Only way I can see, would be to switch the object + id combo used for `wire`. Forcing a full re-render is sometimes helpful when mixing different libraries on a page. Typically when migrating from legacy frameworks to something nice like HyperHTML.

**Comment by WebReflection** [comment]
> So function result can be discarded (if nodes are already in page DOM tree).

I wouldn't do that. The _domdiff_ engine needs to know there is a wire / node. If it finds undefined you gonna have bad time.

You never need to manually append wires so you never need to care about *not* returning those.

The id is to relate a node to an object. How would you create many `<li>` otherwise?

Through a weak relation, and, if needed, a unique `:id` per element (one ref, multiple elements, as [explained in the docs](https://viperhtml.js.org/hyperhtml/documentation/))

> Mixing direct DOM node manipulations (e.g. via jQuery) and wire(obj, id) doesn't work quite as one might expect.

Every obtrusive library that trashes nodes on the DOM is incompatible with hyperHTML and, to be honest, you should never need jQuery at all here.

hyperHTML owns its nodes. If a script invades that territory, it's causing troubles.

This is true for every other framework out there. You mess up with their logic, they fail.

> The node cache in wire will not detect changes to node attributes that are "static" in the template. Perhaps not changes to DOM tree structure either?

If you need to change any attribute, that is a dynamic attribute so ... use hyperHTML to signal that.

Static parts are static, and so would be. You can, however, change attributes, as long as you don't replace the node with something else. In doing so, you can have CSS reacting too, so everything works.

Changing attributes in hyperHTML doesn't trigger anything, re-invoking the template with updated values change attributes.

> Forcing a full re-render is sometimes helpful when mixing different libraries on a page.

That should never be the case. It rather means you don't control what libraries do and you have obtrusive libraries.

However, cleaning the rendering can be forced simply applying a different template.

live pen: https://codepen.io/WebReflection/pen/EdBOgq?editors=0010

```js
const {bind, wire} = hyperHTML;

function setBody(wire) {
  bind(document.body)`${wire}`;
}

function update(ref) {
  return wire(ref)`<p>Hello ${ref.name}</p>`;
}

function clean(ref) {
  return wire(ref)`<!-- clear -->`;
}

const user = {name: 'ag'};

setBody(update(user));

setTimeout(() => {
  setBody(clean(user));
  setTimeout(() =>setBody(update(user)), 1000);
}, 1000);
```

However, you are not the first user that doesn't instantly grasp the declarative nature of hyperHTML so, as I've said before, if you are that kind of person that prefers change everything after instead of declaring what will eventually change, hyperHTML might not be for you, just stick with jQuery.

Otherwise, just try to stop using jQuery 'cause you ain't gonna need it here.

Alternatively, declare nodes that can be used as jQuery target, hoping whatever UI/plugin it is won't be obtrusive with outer nodes too.

I hope you have more answers now. Closing as there's no real action for me to take here (the documentation is also in another repository).

**Comment by cederberg** [comment]
Thank you for the long response. T I didn't make myself very clear initially, so I'll explain more below.

>> So function result can be discarded (if nodes are already in page DOM tree).
>
> I wouldn't do that. The domdiff engine needs to know there is a wire / node. If it finds undefined you gonna have bad time.
>
> You never need to manually append wires so you never need to care about not returning those.

What I've done (and seems to be working properly), is to:

- On initial render (and on each update to whole list) — render with `bind` containing one or more `wire` for each list item.
- In order to disable buttons, adjust icons, etc when user takes action on an item — only call the corresponding `wire` template to update just the node in question (relying on the "side-effect" that cached DOM node is updated in place). This way I don't need to keep full object list around just for making re-renders on minor UI changes like these.
- When action completes — reload full list from server and re-render as per first step. I'm locked to the server-is-master paradigm here.

I don't quite see why this would be dangerous? Both object and DOM nodes are still in scope, so WeakRef should not have been dropped. I'm doing manual DOM updates in the rendered tree (but I did try as how *domdiff* works isn't obvious).

> Every obtrusive library that trashes nodes on the DOM is incompatible with hyperHTML and, to be honest, you should never need jQuery at all here.
>
> hyperHTML owns its nodes. If a script invades that territory, it's causing troubles.
>
> This is true for every other framework out there. You mess up with their logic, they fail.

Look, I don't mind this. But I did read the docs twice without understanding how the DOM node caching and updates actually work (what you call *domdiff* I guess). Think it would be a great addition to the docs to note how `wire` can update DOM nodes, whereas `bind` seems to always create new ones for instance.

Either way, I'm using HyperHTML **just because** it is a library that works well with others. Allowing me to render more and more of the app in a sane way. We have 4 JS frameworks at the moment (not kidding), so going for a fifth clearly wasn't the answer.

Thanks for the great work. I'll try to contribute more actionable patches next time.

**Comment by WebReflection** [comment]
Hey @cederberg with zero code shown it's hard for me to help at all.

**Comment by WebReflection** [comment]
>  bind seems to always create new ones for instance.

no, it doesn't. If there were code to see a minimal example of how you are doing things, I might help.

Neither bind nor wire are supposed to ever create new nodes. This is the very basic of hyperHTML.

**Comment by WebReflection** [comment]
> it always replaces the generated content.

No, it doesn't, or better, it does exactly what you tell it to do.

If you pass an array of strings, you are telling hyperHTML to render it as if it was an `innerHTML` operation, with all the footgun issues that comes with it.

[This is documented already](https://viperhtml.js.org/hyperhtml/documentation/#essentials-8), nothing new to re-document.

There is also a difference between real-world use cases, and people that loop an array of numbers which is meaningless as it is.

This is your example how it's supposed to be in the real world:
https://codepen.io/WebReflection/pen/BGyVQq?editors=0010

The only issue I had in this ticket is the lack of any code to demonstrate your conclusions.

I hope now everything is clear though, if not, please show me other examples, thanks.

**Comment by WebReflection** [comment]
P.S. **maybe** I should add:

> if it's an array of DOM Nodes _or wires_ ...
