### ISSUE TITLE
How do you develop multiple libraries?

### ISSUE THREAD

**Issue by dakom** [WebReflection/hyperHTML#337]
This isn't hyperHTML specific but is more a personal point to you @WebReflection 

Do you have any tips from your experience developing several inder-dependent npm libraries?

i.e. do you use `npm link`, how do you deal with contributions when your local version is unstaged, etc.

Just curious since you seem to manage that really well

**Comment by dakom** [comment]
Feel free to close right away of course, this isn't really an _issue_, just a discussion point around the hyperHTML ecosystem and how it gets built

**Comment by WebReflection** [comment]
> do you use npm link

not at all, I've had bad experience with that in the past and I'm avoiding it at all costs these days

> how do you deal with contributions when your local version is unstaged

I work on branches and rebase from master any time I merge contributions while still working. Then if there are conflicts I fix those and move on. So far never bug conflicts, I guess I've been lucky.

> Do you have any tips from your experience developing several inder-dependent npm libraries?

Just develop as if any of your inter-dependent libraries was a regular 3rd parts, with the exception you can fix those at speed light when needed.

Every time I've switched to monorepo I've bloated time to develop and fix anything, but many out there believe that's the way to go.

However, when you go that direction is also harder to have contributors because the development stack is more complex.

I guess it boils down to the usual: "_it depends_" 👋

**Comment by dakom** [comment]
So you're usually working on one project at a time, then pushing changes, then updating the other project to get the updates before working on that?
