### ISSUE TITLE
failure to create body,head,html tags

### ISSUE THREAD

**Issue by atirip** [WebReflection/hyperHTML#360]
I am not sure if anybody else needs this and it is not difficult to create them without hyperHTML :-), but:

https://codepen.io/anon/pen/VNoodW?editors=0011

		var props={};
		try {
		// crash
			hyperHTML.wire()`
				<html data-foo=${props.foo}>
				<head>
					<meta charset=utf-8>
					<meta name=robots content=noindex>
				</head>
				<body>
				</body>
				</html>
			`;

		} catch(e) {console.log(e)}

		try {
		// crash
			hyperHTML.wire()`<body data-foo=${props.foo}></body>`;
		} catch(e) {console.log(e)}

		try {
		// crash
			hyperHTML.wire()`<head data-foo=${props.foo}></head>`;
		} catch(e) {console.log(e)}

		// works
		hyperHTML.wire()`<section data-foo=${props.foo}></section>`;

**Comment by WebReflection** [comment]
This is a limitation of the standard template tag, example:

```js
var props = {foo: 'bar'};
var t = document.createElement('template');
t.innerHTML = `<html data-foo=${props.foo}>
			<head>
				<meta charset=utf-8>
				<meta name=robots content=noindex>
			</head>
			<body>
			</body>
			</html>`;
t.content.children; // 2, just the meta
```

it's true you can do the via viperHTML, but it's also true it makes no sense to do that with client side templating, since you're looking for trouble if you replace any of those nodes (documentElement, body, head) so, since there are no use cases presented in here, I'll close this too as won't fix.

**Comment by atirip** [comment]
Use case is creating iframes, create html as a string and write it in.

**Comment by WebReflection** [comment]
that's what `document.write` is for.
