### ISSUE TITLE
Uncaught TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/hyperHTML#37]
Just a note, not an issue. 

This example raises the error in the issue title:
```
const items = [1, 2, 3];
const render = hyperHTML.bind(document.body);
render`
    <ul>${items.map(item => hyperHTML.wire(item)`
        <li>${item}</li>
    `)}</ul>
`;
```

This is due to `items` is not an array of objects, as in the examples of the docs.

Fixed with `hyperHTML.wire({item})`, note the curly braces.
Or removing the `.wire` part like 

```
<ul>${items.map(item => `<li>${item}</li>`...
```

Do you think it is worthy adding this little note in the docs?

**Comment by WebReflection** [comment]
You cannot wire primitives 'cause primitives as context make no sense so this is a won't fix.

Just to help you out, you might resolve in at least two better ways.

Using just text will result into HTML injection, which most likely is never what you want.

Use just `.wire()` for one-off operations and **use at least one space around text values**

```js
const items = [1, 2, 3];
const render = hyperHTML.bind(document.body);
render`
    <ul>${items.map(item => hyperHTML.wire()`
        <li> ${item} </li>
    `)}</ul>
`;
```

Alternatively, if you don't want to trash the layout every time you call render and you have a list of primitives instead of objects (which is the common case, here you're basically just playing with something that is basically nothing better than `innerHTML`) you can use the Array index to create unique wires per need.

```js
const wires = [];
const getWire = i => (wires[i] || (wires[i] = hyperHTML.wire()));

const items = [1, 2, 3];
const render = hyperHTML.bind(document.body);
render`
    <ul>${items.map((item, i) => getWire(i)`
        <li> ${item} </li>
    `)}</ul>
`;
```

The [TodoMVC](https://github.com/WebReflection/hypermvc/blob/master/js/views/main.js#L12) is an example of a wired list that doesn't trash nodes each render.

**Comment by albertosantini** [comment]
Thanks for the detailed explanation.

`getWire` trick is nice.

I just filled the issue because I copied and pasted an example from the docs and changed the data structure. You know the result: just in case another user follows my path. I suppose this issue, instead of a note in the README, is enough.

P.S.: After reading `hyperHTML: A Virtual DOM Alternative` post, a masterpiece, I would like to give a try to hyperHTML in [Argo](https://github.com/albertosantini/argo), based on AngularJS, but I need a bit of time.

**Comment by WebReflection** [comment]
it [says](https://github.com/WebReflection/hyperHTML#wait--there-is-a-wire--in-the-code) at the beginning:

> The helper `hyperHTML.wire(obj?)` is ... 

but surely it could be improved. I am planning to create a proper site with better documentation and examples (all written in hyperHTML, of course) but it'll take some time.

Let me know if you need any other help 😉
