### ISSUE TITLE
Potential redundant request with img

### ISSUE THREAD

**Issue by marcoscaceres** [WebReflection/hyperHTML#60]
@WebReflection, sorry, I've not had a chance to investigate this in detail, but it seems what setting `img.src` via hyperHTML can result in unintended network requests because of the generated ID attribute value. 

See 404s here:
https://travis-ci.org/w3c/respec/jobs/243534752

Where, there are things like:
```
/%3C!--_hyper_html:%20836557996;--%3E
```

I think they are coming from (simplified test case): 

```JS
function toLogo(obj) {
  const a = document.createElement("a");
  a.href = obj.href ? obj.href : "";
  a.classList.add("logo");
  return hyperHTML.bind(a)`
    <span id="${obj.id}">
      <img
        alt="${obj.alt}"
        src="${obj.src}"
        width="${obj.width}"
        height="${obj.height}">
    </span>`;
}

const  a = toLogo({ src: "test",  alt: "alt test", width: "123", height: "123", id: "foo"});
document.body.appendChild(a); 
```

I've not been able to reproduce by pasting into developer console, but can see the GET request initiated in by the image in the network tab in Safari. 

See, for example:
https://w3c.github.io/browser-payment-api/

**Comment by WebReflection** [comment]
It's inevitable right now and a known "issue"

### why it's inevitable
there is no parser whatsoever in `hyperHTML`, strings are injected once as these are with comments in there.

This might result in some warning for some attribute that requires network requests or special meaning (i.e. a style attribute that is invalid due comment content in there).

### why it's not always an issue
it's browser dependent. Some browser is smart enough to understand there is a comment in the `src` attribute, some other will URL encode it and try to request it no matter what.

Safari might be one of the latter cases.

### possible solutions
I need to investigate if on a DOM node that is not live this happens as well. If it doesn't it might be worth exploring the possibility to always create the first pass offline (document-fragment) and append such fragment instead of using innerHTML for the first pass.

To be honest, this might even result in better performance for bigger bound containers 'cause some attribute might force layour repaint/reflow while trasversed via hyperHTML.

However, if the offline first-pass solution won't work, I'll need to create a smart RegExp that catches special network related attributes and put in there some invalid  dummy `data:uri` value that might still trigger some warning but hey ... I don't see many other options here :man_shrugging: 

### as summary
There's **a lot** going on right now on this repo and while I know this might be an issue in some case, I don't consider it a real blocker so it won't have highest priority **but** I will try to fix it by the end of the next week.

**Comment by joshgillies** [comment]
@marcoscaceres I think this can be resolved by manually assigning the `img.src` attribute, similar to this in the docs: https://github.com/WebReflection/hyperHTML#attributes-resolved-offline-might-show-warnings

**Comment by WebReflection** [comment]
thanks @joshgillies that's a possible work around too

**Comment by marcoscaceres** [comment]
@joshgillies, yep,  might do as the doc suggest there. Seems simplest. 

@WebReflection if there are browsers that understand `<!-- foo -->` as comments in attributes, then we can push to have that be standardized behavior. Let me know.

**Comment by WebReflection** [comment]
You can indeed currently work around like this:
```js
function toLogo(obj) {
  const a = document.createElement("a");
  a.href = obj.href ? obj.href : "";
  a.classList.add("logo");
  hyperHTML.bind(a)`
    <span id="${obj.id}">
      <img
        alt="${obj.alt}"
        width="${obj.width}"
        height="${obj.height}">
    </span>`;
  a.querySelector('img').src = obj.src;
  return a;
}
```

or actually, since you create the element at runtime, use a wire
```js
function toLogo(obj) {
  const a = hyperHTML.wire(obj)`
  <a class="logo">
    <span id="${obj.id}">
      <img
        alt="${obj.alt}"
        width="${obj.width}"
        height="${obj.height}">
    </span>
  </a>
  `;
  if (obj.href) a.href = obj.href;
  a.querySelector('img').src = obj.src;
  return a;
}
```
this will also guarantee if you pass the same object twice no new element is created (use just `hyperHTML.wire()` without object if meant to be created each time)

To be honestI wonder if you could change your example and use a wire instead to confirm in that case the problem is solved (since wires are created offline)

**Comment by WebReflection** [comment]
about that

> if there are browsers that understand  as comments in attributes, then we can push to have that be standardized behavior. Let me know.

I've just tried this in Chrome and Firefox console and indeed no network whatsoever is triggered at all.

```js
document.body.innerHTML =
  '<img src="<!--_hyper_html:%20836557996;-->">'
```

**Comment by marcoscaceres** [comment]
Firefox is weird :) It's producing a request... but yes, it's not sending it to the network. 

![screenshot 2017-06-19 17 12 37](https://user-images.githubusercontent.com/870154/27273488-9b8d2782-5512-11e7-86c6-7398988b47d7.png)

**Comment by marcoscaceres** [comment]
Ok, closing this as non-issue... will move this to the DOM Parsing spec.
