### ISSUE TITLE
Rendering <style> elements

### ISSUE THREAD

**Issue by guitarino** [WebReflection/hyperHTML#7]
Hi Andrea, thanks for another great library.

There's an annoying problem with rendering <style> elements that results in an error. Here's a simple use-case:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="hyperHTML.js"></script>
    <style id="style"></style>
</head>
<body>
    <div class="content"></div>
    <div class="content"></div>
    <script src="main.js"></script>
</body>
</html>
```

and *main.js*

```javascript
function tick(render) {
  render`.content:before {
    content: '${new Date().toLocaleTimeString()}';
  }`;
}
setInterval(tick, 1000,
  hyperHTML.bind(document.getElementById('style'))
);
```

This results in an error and the output showing
```
<!--_hyperHTML247232086-->
<!--_hyperHTML247232086-->
```

Instead of the expected
```
15:23:31
15:23:31
```

The cause is that whatever is inside <style> tag is automatically treated as a text node and so, the comment tag  is instead treated as part of that text node instead of a separate comment. A possible solution is to create the nodes inside a temporary `<div>` and then transfer them to the `<style>` element.

However, to be honest I think this is a very rare use-case and perhaps isn't worth fixing. Still, I wanted to report the issue.

Cheers.

**Comment by WebReflection** [comment]
Nope, you can't do that. `hyperHTML` maps attributes and node, not just string content. To do that, you don't need `hyperHTML` but just template literals.

```js
function tick(style) {
  style.textContent = `.content:before {
    content: '${new Date().toLocaleTimeString()}';
  }`;
}
setInterval(tick, 1000,
  document.getElementById('style')
);
```

`hyperHTML` is for:

  * HTML content, not style text
  * attributes as a whole, not partial attributes since that's [YAGNI](https://github.com/WebReflection/hyperHTML/blob/master/DEEPDIVE.md#attributes-the-right-way)
  * wired fragments

For everything else you can use just template literals 😉
