### ISSUE TITLE
compile to TypeScript problems?

### ISSUE THREAD

**Issue by gdi2290** [WebReflection/hyperHTML#91]
https://github.com/Microsoft/TypeScript/issues/17956

**Comment by WebReflection** [comment]
hyperHTML is all about promoting standards, people choosing non-standards decided their own pattern.

regardless, there's nothing hyperHTML can do to avoid TypeScript issues so thanks a lot for the heads-up, but I think I am going to close this since they need to fix it.

I also find it quite hilarious lit-html used TypeScript to develop something incompatible with TypeScript
