### ISSUE TITLE
Compatibility table for es6 compilers?

### ISSUE THREAD

**Issue by katywings** [WebReflection/hyperHTML#99]
Hey Andrea, i just watched [your talk](https://skillsmatter.com/skillscasts/10805-an-isomorphic-journey-to-a-lighter-and-blazing-fast-virtual-dom-alternative) and was amazed about its depth - thanks for the details! 

One question arrived when you mentioned the typescript compilation of tagged template literals: as a [Buble](https://buble.surge.sh/guide/#dangerous-transforms) user i was wondering how they are doing it and it looks like they doesnt even have enabled tagged tl's by default and use typescripts compilation method in the other case. I need to try it out, but it looks like hyperHTML is only compatible with Babel as ES6 compiler right? Are there any escape hatches for this? :)

In the README you basically indirectly mentioned this anyway:

> Also compatible with Babel transpiled output

I think, not all people would interpret this like: "Only compatible with Native ES6 or ES6 by Babel" and would just think: "Oh when its working with Babel, then its basically also working with Buble! And it could be a place of frustration for newcomers! *So all I want to actually say: maybe this should be mentioned more explicit - or even with a little compiler support table or so ;)*

Last but not least: i like your effort, keep up the cool ideas! ☕️

**Comment by WebReflection** [comment]
Hi @katywings , thanks for sharing my own talk I wasn't even aware it was live already!!!!

I'll try to answer as I can to your questions.

> it looks like hyperHTML is only compatible with Babel as ES6 compiler right?

hyperHTML is 100% compatible with **ECMAScript Standard**. If transpilers are not compliant, [like it is for TypeScript](https://github.com/Microsoft/TypeScript/issues/17956), it's not an hyperHTML compatibility issue, isn't it? :wink: 

_TL;DR_ you don't need any compiler/transpiler to user hyperHTML ... actually, these days, the less you transpile the safer you'll code.

However, Babel got Template Literals transpiled well.

>  "Oh when its working with Babel, then its basically also working with Buble! And it could be a place of frustration for newcomers!

Your frustration comes from Microsoft TypeScript project [ignoring on purpose](https://twitter.com/AdamRackis/status/902185503377772545) specs compliant implementation of template literals.

Please rise your voice there, because hyperHTML has no fault whatsoever about that.

Apologies if this is not the answer you were hoping for. All I can say is that scarying developers because they chose a non standard language is not the purpose of this project, I rather push TypeScript to fix their issues ASAP.

**Comment by WebReflection** [comment]
Hi @katywings ,
  I'd like to inform you that after a long discussion on TypeScript repository, a work around to feature detect TypeScript bad compilation came out.

As result, I've pushed a patched version of _hyperHTML_ that will work on your environment too.

Please try latest `v1.6.7` and let me know if everything is fine.

Thanks for making this happen, I wouldn't have pushed much if it wasn't for you.

Best Regards

**Comment by katywings** [comment]
@WebReflection

First and foremost, thanks again for your engagement! Now i need to say, your first answer sounded like you misinterpreted me :): I actually really just opened this issue to warn you about the potential of user frustration - not because i was in any way frustrated by myself - i mean i didnt even try it out xD, i just added one and one together when i heard Typescript problems and therefore also potential Buble problems. And as a library author by myself i know how fast user opinions can be pulled into the negative zone ^^!

About non-transpilation strategies: i personally am not in hurry to remove the build step - just feeling like its some months too early ;)...

But now after you did so much I really need to give hyperHTML a try, right?!!! :D - probably have some "minutes" this weekend - hopefully! Currently my todo list's pagination is over 9000...

**Comment by WebReflection** [comment]
ah yeah ... Todos ... you can do that too https://github.com/WebReflection/hypermvc :smile: 

Btw I did misunderstood your initial post indeed, apologies for that.

If you'll ever have time to try it out, please don't hesitate to ping me if needed (there is also a [new StackOverflow tag for it](https://stackoverflow.com/questions/tagged/hyperhtml))

Best Regards
